name: GitHub Actions Build Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install and Build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm install
          npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: src/.vuepress/dist
